### PR TITLE
3.5 User search functionality

### PR DESCRIPTION
**Pull request by eddyChai**
Implementation of:
3.5.1 Search Bar
3.5.2 Search Function
3.5.3 Search results

### CODE REVIEW

**Review by ANUBARY — CHANGES_REQUESTED** [review]
lacks commenting in code

**Comment by eddyChai** [comment]
Aright please have a look at the current commit. I've put in some comments.

**Review by ANUBARY — APPROVED** [review]
the new changes looks good

**Comment by eddyChai** [comment]
Thanks! Merge it when possible.

**Pull request merged**
